### ISSUE TITLE
Interoperability with Pimutils and the Vdir format

### ISSUE THREAD

**Issue by Mayeu** [etesync/cli-client#1]
Hello :wave:,

Nice work with EteSync! Love that it makes this level of privacy possible :pray:

May I suggest that CLI tool be interoperable with the @pimutils project, more particularly with the [Vdir storage format](https://vdirsyncer.pimutils.org/en/stable/vdir.html)?

Could be pretty awesome :)

**Comment by tasn** [comment]
Hey,

vdirsyncer has native EteSync support. Take a look [here](https://github.com/pimutils/vdirsyncer/blob/master/docs/config.rst#etesync).

Is this what you're looking for?

**Comment by Mayeu** [comment]
Oh I missed that!

That's awesome :smile: sorry for the noise :pray:

**Comment by tasn** [comment]
All good. :)

Please let me know if you have any comments.
